services:
  - type: web
    name: mediafetch-bot
    env: python
    buildCommand: pip install -r requirements.txt && apt-get install -y ffmpeg
    startCommand: python app.py
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: APP_URL
        sync: false
      - key: PORT
        value: 8080
