services:
  - type: web
    name: mediafetch-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: mediafetch
      - key: PORT
        value: 8080
      - key: APP_URL
        sync: false          # set to your Render URL e.g. https://mediafetch-bot.onrender.com
      - key: PING_INTERVAL
        value: 280           # slightly under Render's 5-min sleep window
